sudo: false
language: go

os:
  - linux
  - osx
  - windows

go:
  - "1.11.x"
  - master

matrix:
  allow_failures:
    - go: master

install:
  - make setup

script:
  - go build ./_example/simple-echo/main.go
  - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(echo -n "")
  - make lint
  - make test
