sudo: false
language: go

os:
  - linux
  - osx
  - windows

go:
  - "1.11.x"
  - master

install:
  - make setup

script:
  - go build ./_example/simple-echo/main.go
  - make lint
  - make test
  - make race-test
