sudo: false
language: go

go:
  - "1.11.x"
  - tip

os:
  - linux
  - osx
  - windows

install:
  - go get -u golang.org/x/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

stages:
  - lint
  - examples
  - test

jobs:
  include:
    - stage: lint
      script:
        - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(echo -n "")
        - make lint
      go: "1.11.x"
      os: osx
    - stage: examples
      script:
        - ./_example/build.sh
      go: "1.11.x"
      os: osx

script:
  - go test -race ./...

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - os: windows
