sudo: false
language: go

go:
  - "1.11.x"
  - tip

os:
  - linux
  - osx
  - windows

install:
  - make setup

jobs:
  include:
    - stage: Lint
      script:
        - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(echo -n "")
        - make lint
      go: "1.11.x"
      os: osx
    - stage: Build
      script:
        - make build
    - stage: Unit Test
      script:
        - make test
  allow_failures:
    - go: tip
