sudo: false
language: go

install:
  - make setup

jobs:
  include:
    - stage: Lint
      script:
        - go build ./_example/simple-echo/main.go
        - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(echo -n "")
        - make lint
      go: "1.11.x"
      os: osx
    - stage: Build
      script:
        - make build
      go:
        - "1.11.x"
        - tip
      os:
        - linux
        - osx
        - windows
    - stage: Unit Test
      script:
        - make test
      go:
        - "1.11.x"
        - tip
      os:
        - linux
        - osx
        - windows
  allow_failures:
    - go: tip

script:
  - go build ./_example/simple-echo/main.go
  - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(echo -n "")
  - make lint
  - make test
