sudo: false
language: go

go:
  - "1.11.x"
  - tip

os:
  - linux
  - osx
  - windows

install:
  - make setup

jobs:
  include:
    - stage: Lint
      script:
        - diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*")) <(echo -n "")
        - make lint
      go: "1.11.x"
      os: osx

script:
  - make test
  - make build

matrix:
  allow_failures:
    - go: tip
    - os: windows
