// Code generated by "stringer -type=Key"; DO NOT EDIT.

package prompt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Escape-0]
	_ = x[ControlA-1]
	_ = x[ControlB-2]
	_ = x[ControlC-3]
	_ = x[ControlD-4]
	_ = x[ControlE-5]
	_ = x[ControlF-6]
	_ = x[ControlG-7]
	_ = x[ControlH-8]
	_ = x[ControlI-9]
	_ = x[ControlJ-10]
	_ = x[ControlK-11]
	_ = x[ControlL-12]
	_ = x[ControlM-13]
	_ = x[ControlN-14]
	_ = x[ControlO-15]
	_ = x[ControlP-16]
	_ = x[ControlQ-17]
	_ = x[ControlR-18]
	_ = x[ControlS-19]
	_ = x[ControlT-20]
	_ = x[ControlU-21]
	_ = x[ControlV-22]
	_ = x[ControlW-23]
	_ = x[ControlX-24]
	_ = x[ControlY-25]
	_ = x[ControlZ-26]
	_ = x[ControlSpace-27]
	_ = x[ControlBackslash-28]
	_ = x[ControlSquareClose-29]
	_ = x[ControlCircumflex-30]
	_ = x[ControlUnderscore-31]
	_ = x[ControlLeft-32]
	_ = x[ControlRight-33]
	_ = x[ControlUp-34]
	_ = x[ControlDown-35]
	_ = x[Up-36]
	_ = x[Down-37]
	_ = x[Right-38]
	_ = x[Left-39]
	_ = x[ShiftLeft-40]
	_ = x[ShiftUp-41]
	_ = x[ShiftDown-42]
	_ = x[ShiftRight-43]
	_ = x[Home-44]
	_ = x[End-45]
	_ = x[Delete-46]
	_ = x[ShiftDelete-47]
	_ = x[ControlDelete-48]
	_ = x[PageUp-49]
	_ = x[PageDown-50]
	_ = x[BackTab-51]
	_ = x[Insert-52]
	_ = x[Backspace-53]
	_ = x[Tab-54]
	_ = x[Enter-55]
	_ = x[F1-56]
	_ = x[F2-57]
	_ = x[F3-58]
	_ = x[F4-59]
	_ = x[F5-60]
	_ = x[F6-61]
	_ = x[F7-62]
	_ = x[F8-63]
	_ = x[F9-64]
	_ = x[F10-65]
	_ = x[F11-66]
	_ = x[F12-67]
	_ = x[F13-68]
	_ = x[F14-69]
	_ = x[F15-70]
	_ = x[F16-71]
	_ = x[F17-72]
	_ = x[F18-73]
	_ = x[F19-74]
	_ = x[F20-75]
	_ = x[F21-76]
	_ = x[F22-77]
	_ = x[F23-78]
	_ = x[F24-79]
	_ = x[Any-80]
	_ = x[CPRResponse-81]
	_ = x[Vt100MouseEvent-82]
	_ = x[WindowsMouseEvent-83]
	_ = x[BracketedPaste-84]
	_ = x[Ignore-85]
	_ = x[NotDefined-86]
}

const _Key_name = "EscapeControlAControlBControlCControlDControlEControlFControlGControlHControlIControlJControlKControlLControlMControlNControlOControlPControlQControlRControlSControlTControlUControlVControlWControlXControlYControlZControlSpaceControlBackslashControlSquareCloseControlCircumflexControlUnderscoreControlLeftControlRightControlUpControlDownUpDownRightLeftShiftLeftShiftUpShiftDownShiftRightHomeEndDeleteShiftDeleteControlDeletePageUpPageDownBackTabInsertBackspaceTabEnterF1F2F3F4F5F6F7F8F9F10F11F12F13F14F15F16F17F18F19F20F21F22F23F24AnyCPRResponseVt100MouseEventWindowsMouseEventBracketedPasteIgnoreNotDefined"

var _Key_index = [...]uint16{0, 6, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86, 94, 102, 110, 118, 126, 134, 142, 150, 158, 166, 174, 182, 190, 198, 206, 214, 226, 242, 260, 277, 294, 305, 317, 326, 337, 339, 343, 348, 352, 361, 368, 377, 387, 391, 394, 400, 411, 424, 430, 438, 445, 451, 460, 463, 468, 470, 472, 474, 476, 478, 480, 482, 484, 486, 489, 492, 495, 498, 501, 504, 507, 510, 513, 516, 519, 522, 525, 528, 531, 534, 545, 560, 577, 591, 597, 607}

func (i Key) String() string {
	if i < 0 || i >= Key(len(_Key_index)-1) {
		return "Key(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Key_name[_Key_index[i]:_Key_index[i+1]]
}
